fix: dropdownButton useMemo error
xsky-fe/wizard-ui pull request #196
Opened 2022-11-18 10:44 UTC by xskyAlex

Signed-off-by: zhanghuan [zhang.huan@xsky.com](mailto:zhang.huan@xsky.com)

关联pr: https://github.com/xsky-fe/wizard-ui/pull/192
问题：在非react组件用了 useMemo,在xsky-wizard安装运行时本地报错

引入了reselect在普通函数做数据缓存

2022-11-23 03:57 UTC, jz903 approved these changes

2022-11-23 06:55 UTC, jz903 requested changes

2022-11-23 06:55 UTC, jz903 commented on src/components/DropdownButton/index.tsx
> +      {parsedMenu ? renderContent(parsedMenu, setButtonOpen, open) : children}
如果还是在原来递归里加randomId, 可以如下避免不必要的渲染
```
const memorizedMenu = useMemo(() => {
  return menu ? renderContent(parsedMenu, setButtonOpen, open) : children;
}, [menu])
...
```

2022-11-23 09:34 UTC, xskyAlex commented on src/components/DropdownButton/index.tsx
> +      {parsedMenu ? renderContent(parsedMenu, setButtonOpen, open) : children}
已修改。添加 是否修改menu的标示 来判断是否需要生成key

2022-11-24 01:59 UTC, jz903 approved these changes

2022-11-24 02:12 UTC, merged