fix: ui style
xsky-fe/wizard-ui pull request #276
Opened 2023-07-19 08:20 UTC by hcyooooo

2023-07-27 07:05 UTC, pangkaiguo requested changes

2023-07-27 07:05 UTC, pangkaiguo commented on src/components/DatePicker/style.scss
> +  top: 34px;
这个定位是干嘛用的？如果是因为业务侧的问题，应该在业务侧使用时定义。不应该在组件库本身加

2023-07-27 07:05 UTC, pangkaiguo commented on src/components/Modal/style.scss
> +    padding: 32px 24px;
modal 的padding直接变更是什么原因？？这个变更可能会导致对话框底部样式错乱

2023-07-27 07:08 UTC, pangkaiguo commented
这些验收变更，没有经过测试，只有 wizard-ui 本身的变更。
需要注意两点：
1、wizard-ui 本身变更和自测没有问题；
2、wizard-ui 变更后的内容在 wizard 验证通过，如果wizard也要对应做调整，则把 wizard 关联的变更 pr 一起在这里关联体现。否则这个 pr 不能合入。

2023-07-27 07:51 UTC, hcyooooo commented on src/components/DatePicker/style.scss
> +  top: 34px;
![image](https://github.com/xsky-fe/wizard-ui/assets/102645439/32b1e6fe-ea22-40c1-9ad5-e1035492388e)

2023-07-27 07:52 UTC, hcyooooo commented on src/components/Modal/style.scss
> +    padding: 32px 24px;
![image](https://github.com/xsky-fe/wizard-ui/assets/102645439/93b13da7-f23e-4f42-92e4-2bec9d7182ad)

2023-07-28 06:25 UTC, pangkaiguo commented on src/components/DatePicker/style.scss
> +  top: 34px;
你先感受一下改完后的交互。点击输入框能收起吗？交互逻辑是不是存在 bug

2023-07-28 06:26 UTC, pangkaiguo commented on src/components/Modal/style.scss
> +    padding: 32px 24px;
这个 modal 的变更也一样是会引入大批问题。

2023-08-01 10:08 UTC, merged